### PR TITLE
Fix shell portability issue on NetBSD

### PR DESCRIPTION
**Pull request by krytarowski**

### CODE REVIEW

**Comment by wscott** [comment]
You realize this cset patches 'src/gui/tcltk/tcl/win/configure' for NetBSD compatibility and yet
that is the config file for building on Windows?
We have NetBSD in our build cluster and ship NetBSD binaries.

That said, I agree using == with 'test' on a shell script is bad practice.

**Comment by krytarowski** [comment]
pkgsrc scans shell scripts and blocks when finds common portability problems. It blocked the build due to this '=='.

**Comment by wscott** [comment]
Interesting.
OK. I will make the change in our bk source repository and get it included in the next release.

**Comment by wscott** [comment]
The current release includes this patch.  Thanks!

**Pull request closed without merging**
